### PR TITLE
Update mboximport.dtd

### PR DESCRIPTION
**Pull request by DenB10**
Just typo fix

### CODE REVIEW

**Comment by cleidigh** [comment]
@DenB10 
I think this completes all outstanding fr updates, right?
@cleidigh

**Comment by DenB10** [comment]
@cleidigh
C’est tout bon pour moi, ready to release?

**Comment by cleidigh** [comment]
@DenB10 
Doing spot testing and a look at profile stuff (definitely can of worms)
goal is I push b7 today and into review Q by Sunday unless someone reports a fowl up.
@cleidigh

**Comment by DenB10** [comment]
@cleidigh 
All right! I think you've done a hell of a job with this version 14.0.1, which should be renamed 14.1.0 because so much has been done since 14.0.0.
As for profile import-export, I think it's already quite functional, but I haven't delved too deeply into it, "wait and see" as they say.
Have a good weekend and see you soon for more adventures! For my part, I'm going to test some wines at a wine fair.

**Comment by cleidigh** [comment]
@DenB10 
Well wine tasting sounds like a terrific way to end the week.
Nothing like a good Bordeaux or Cabernet Franc!
Wish I could still drink.
B7 is up and out on Sunday.

Enjoy yourself, and Salud!
Christopher

**Comment by DenB10** [comment]
>Wish I could still drink.

I'm sorry if I've made you feel bitter, but I won't do it again.

Denis

**Comment by cleidigh** [comment]
Denis
Absolutely not!
I love to hear what people are doing, for me working with everyone is a big part of enjoying everything.
Did you find some good wines?
What region are you in?
I enjoy when others do.
Christopher

**Comment by DenB10** [comment]
Sorry for the late reply, I'm not sulking but you didn't understand that I was away for the whole weekend (but I didn't drink the whole time ;-).
I bought a few bottles of Bordeaux Côtes de Bourg (excellent!) and Anjou (Loire Valley) in Reims (Champagne region).
I invite you to come and taste one or two with me, at least virtually :-)

>I love to hear what people are doing, for me working with everyone is a big part of enjoying everything.

I understood from all your posts that you love people.

Merci et à bientôt,

Denis

**Comment by cleidigh** [comment]
Denis
Sounds like a great weekend!
I have not had either wine, but I am curious about the Bordeaux.
Is it one of the deep rich tannic Bordeaux s?
I love those.
And I am still curious where in France you reside.
While originally from Brooklyn NY, I now live in Providence, Rhode Island
about 40min South of Boston.

Christopher

**Comment by DenB10** [comment]
Bordeaux is my favorite red wine, especially from the Médoc and Graves regions, where Cabernet Sauvignon predominates. The one I bought is predominantly Merlot and is rich, tannic and long on the palate, just the way you like it. (Does your mouth water?)

I live in a small town north of Troyes (Champagne region) about 130 km southeast of Paris.

Denis

**Comment by cleidigh** [comment]
Denis oh boy am I jealous (and yes indeed my mouth is salivating)!
It sounds like we have a common admiration.
Back in the day I was neither a wine snob nor any expert, I did , however, have a pretty good pallet and certainly knew good wines. I love Bordeauxs and the best wine I ever had was a Château Margaux Saint Emillion vintage 82 or 83. My wife's business associate and friend from Neunkerchen Saarland DE is a wine connoisseur who used to send us spectacular wines before customs made it impossible.
So we have been spoiled.

I unfortunately never made it to wine country in France. I can imagine though having been to several others. I will envision your locale as idyllic!

Next thread I will tell you about our best friends that created an amazing Vinyard completely from scratch right here in little Rhode Island!
Christopher

**Comment by DenB10** [comment]
Wine is above all a pleasure, but a pleasure that comes at a cost. At around 500 euros a bottle of Château Margaux (1er grand cru classé, Margaux appellation, not Saint-Émilion), it's a pleasure I can't afford. If your friend has already given you a bottle of this wine, he must be a very good friend and you should keep it :-)
Fortunately, I can find much less expensive wines that give me a lot of pleasure. The important thing is to drink it in good company (friends, family).

I don't think wine is exclusive to France or Italy or Spain, because there are good wines all over the world. For example, on my only trip to America (Quebec, Canada), I tasted a Californian wine from Napa Valley that was very good, so why not Rhode Island?

Note: we're a long way from IENG, aren't we?

**Comment by cleidigh** [comment]
Denis
If you wish we can continue whenever more privately if you send email to my test account I will respond on my normal email.

I do have one IETNG question. Have you tried exporting to pdf with right click on a message and right click in the message display?
I got two lousy reviews last night saying pdf export not working.
My test account : 
test1@kokkini.net
Christopher

**Comment by DenB10** [comment]
>If you wish we can continue whenever more privately if you send email to my test account I will respond on my normal email.

Okay, got it.

>I do have one IETNG question. Have you tried exporting to pdf with right click on a message and right click in the message >display?
>I got two lousy reviews last night saying pdf export not working.

I've seen these reviews on ATN.
The pdf export works well for me (Win 7, Betterbird 115.4.2, IETNG v14.0.1), both via the context menu in the message list and via the context menu in the message display. I don't understand these two people's problem.

**Pull request merged**
