### PR TITLE
TB91

### PR DESCRIPTION
**Pull request by jobisoft**
This hopefully gets most of the functionality back into a working state.

I refuse to work around/with old legacy code, so this PR removes a bunch of old code and sets a min version of 91.0

Not fixed are:
- PDF export
- The backup menu entry in the IET menu in the tools menu does not do anything (it was broken in the current released version for TB78 already, was it not?)

### CODE REVIEW

**Comment by jobisoft** [comment]
This is a version to try:
[TB91_beta2.zip](https://github.com/thundernest/import-export-tools-ng/files/7160263/TB91_beta2.zip)

**Comment by jobisoft** [comment]
This is beta3 for Thunderbird 91 with #266 and #259 fixed as well.
[TB91_beta3.zip](https://github.com/thundernest/import-export-tools-ng/files/7162977/TB91_beta3.zip)

**Comment by ostefano** [comment]
@jobisoft willing to test it, but I am on the beta channel. Is it easy to relax the version constraint to include 93 as well?

**Comment by jobisoft** [comment]
Yes, someone did already say it worked in TB93. Here a beta4 with relaxed limits:
[TB91_beta4.zip](https://github.com/thundernest/import-export-tools-ng/files/7165087/TB91_beta4.zip)

**Comment by ostefano** [comment]
Awesome. Installs and imports mbox files perfectly. Thanks!

**Comment by jobisoft** [comment]
Further update progress is documented here:
https://github.com/thundernest/import-export-tools-ng/issues/264

**Pull request merged**
