### PR TITLE
A few updates

### PR DESCRIPTION
**Pull request by ovari**

### CODE REVIEW

**Comment by ovari** [comment]
Could you please advise when this is merged so that our fork can be deleted? Thank you

**Comment by ovari** [comment]
@cleidigh can our fork be deleted? Thank you

**Comment by cleidigh** [comment]
@ovari 
Sorry for taking so long.  I am starting a new branch for the next Release this weekend and I will merge this into that.  Appreciate the fixes!
@cleidigh

**Comment by ovari** [comment]
@cleidigh thanks for your reply. Please advise when we can delete our fork.

**Comment by cleidigh** [comment]
@ovari 
Done.
You may be interested in checking out #75 within beta 15 or greater.
Thanks!

**Pull request closed without merging**
